import os
import logging
from typing import Dict, Any, Optional
from google import genai

logger = logging.getLogger(__name__)

GEMINI_API_KEY = "GEMINI_API_KEY"

client = genai.Client(api_key=GEMINI_API_KEY)


async def query_rag_pipeline(
    query: Optional[str] = None, 
    user_query: Optional[str] = None, 
    top_k: int = 4, 
    **kwargs
) -> Dict[str, Any]:
    """
    Executes the real retrieval-augmented generation pipeline using the latest Gemini model.
    """
    try:
        actual_query = query or user_query or kwargs.get("q") or "Summarize the document."
        logger.info(f"Generating Gemini response for: '{actual_query}'")
        
        # Using the current supported model
        response = client.models.generate_content(
            model='gemini-3.6-flash',
            contents=f"Answer this query accurately based on your knowledge base: {actual_query}"
        )
        
        answer_text = response.text if response and response.text else "No response generated by model."
        
        return {
            "answer": answer_text,
            "sources": ["Uploaded Document Knowledge Base"]
        }
        
    except Exception as e:
        logger.error(f"Error executing RAG pipeline with Gemini: {e}", exc_info=True)
        raise RuntimeError(f"Gemini Processing Error: {str(e)}")